730-Proj0: pmap_clnt.h File Reference
pmap_clnt.h File Reference
#include <features.h>
#include <rpc/types.h>
#include <rpc/xdr.h>
#include <rpc/clnt.h>
Functions
bool_t pmap_set (__const u_long __program, __const u_long __vers, int __protocol, u_short __port) __THROW
bool_t pmap_unset (__const u_long __program, __const u_long __vers) __THROW
struct pmaplist * pmap_getmaps (struct sockaddr_in *__address) __THROW
enum clnt_stat pmap_rmtcall (struct sockaddr_in *__addr, __const u_long __prog, __const u_long __vers, __const u_long __proc, xdrproc_t __xdrargs, caddr_t __argsp, xdrproc_t __xdrres, caddr_t __resp, struct timeval __tout, u_long *__port_ptr) __THROW
enum clnt_stat clnt_broadcast (__const u_long __prog, __const u_long __vers, __const u_long __proc, xdrproc_t __xargs, caddr_t __argsp, xdrproc_t __xresults, caddr_t __resultsp, resultproc_t __eachresult) __THROW
u_short pmap_getport (struct sockaddr_in *__address, __const u_long __program, __const u_long __version, u_int __protocol) __THROW
Variables
__BEGIN_DECLS typedef bool_t(* resultproc_t)(caddr_t __resp, struct sockaddr_in *__raddr)
Function Documentation
enum clnt_stat clnt_broadcast (__const u_long __prog, __const u_long __vers, __const u_long __proc, xdrproc_t __xargs, caddr_t __argsp, xdrproc_t __xresults, caddr_t __resultsp, resultproc_t __eachresult)
struct pmaplist* pmap_getmaps (struct sockaddr_in * __address) [read]
u_short pmap_getport (struct sockaddr_in * __address, __const u_long __program, __const u_long __version, u_int __protocol)
enum clnt_stat pmap_rmtcall (struct sockaddr_in * __addr, __const u_long __prog, __const u_long __vers, __const u_long __proc, xdrproc_t __xdrargs, caddr_t __argsp, xdrproc_t __xdrres, caddr_t __resp, struct timeval __tout, u_long * __port_ptr)
bool_t pmap_set (__const u_long __program, __const u_long __vers, int __protocol, u_short __port)
Referenced by findTransient().
bool_t pmap_unset (__const u_long __program, __const u_long __vers)
Referenced by die(), endtheclient(), and main().
Variable Documentation
__BEGIN_DECLS typedef bool_t(* resultproc_t)(caddr_t __resp, struct sockaddr_in *__raddr)
Definition at line 45 of file pmap_clnt.h.