730-Proj0: server_clnt.c File Reference
server_clnt.c File Reference
#include <memory.h>
#include "server.h"
Functions
int * addclient_1 (ClientData *argp, CLIENT *clnt)
int * delclient_1 (ClientData *argp, CLIENT *clnt)
int * addline_1 (AddLineArg *argp, CLIENT *clnt)
Linep * sendallmylines_1 (ClientData *argp, CLIENT *clnt)
Variables
static struct timeval TIMEOUT = { 25, 0 }
Function Documentation
int* addclient_1 (ClientData * argp, CLIENT * clnt)
Definition at line 13 of file server_clnt.c.
References addclient, clnt_call, NULL, RPC_SUCCESS, TIMEOUT, xdr_ClientData(), and xdr_int().
int* addline_1 (AddLineArg * argp, CLIENT * clnt)
Definition at line 43 of file server_clnt.c.
References addline, clnt_call, NULL, RPC_SUCCESS, TIMEOUT, xdr_AddLineArg(), and xdr_int().
int* delclient_1 (ClientData * argp, CLIENT * clnt)
Definition at line 28 of file server_clnt.c.
References clnt_call, delclient, NULL, RPC_SUCCESS, TIMEOUT, xdr_ClientData(), and xdr_int().
Linep* sendallmylines_1 (ClientData * argp, CLIENT * clnt)
Definition at line 58 of file server_clnt.c.
References clnt_call, NULL, RPC_SUCCESS, sendallmylines, TIMEOUT, xdr_ClientData(), and xdr_Linep().
Variable Documentation
struct timeval TIMEOUT = { 25, 0 } [static]
Definition at line 10 of file server_clnt.c.
Referenced by addclient_1(), addline_1(), delclient_1(), and sendallmylines_1().