730-Proj0: client_s.c File Reference
client_s.c File Reference
#include "client.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
Defines
#define SIG_PF void(*)(int)
Functions
static void whiteboardclient_1 (struct svc_req *rqstp, register SVCXPRT *transp)
int getTransientProgNumber (int version)
void startclient (int, int, char *, char *, char *, char *)
Called by client_s.c. See ./ed-script. Start the client.
int main (int argc, char *argv[])
Define Documentation
#define SIG_PF void(*)(int)
Definition at line 16 of file client_s.c.
Function Documentation
int getTransientProgNumber (int version)
Definition at line 48 of file transient.c.
References findTransient(), and NATTEMPTS.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 65 of file client_s.c.
References getTransientProgNumber(), NULL, pmap_unset(), RPC_ANYSOCK, startclient(), svc_register(), svc_run(), svctcp_create(), svcudp_create(), WhiteBoardClient, whiteboardclient_1(), and WhiteBoardClientVersion.
void startclient (int nprogram, int nversion, char * servermcnm, char * boardnm, char * xdisplaynm, char * pmcolor)
Called by client_s.c. See ./ed-script. Start the client.
Parameters:
nprogram program number in client/server file interface.
nversion version number in interface file. servermcnm name of server machine.
boardnm name of white board.
xdisplaynm name of display, similar to the DISPLAY env variable.
pmcolor color of paint.
Returns:
void.
Definition at line 160 of file client.c.
References addclient_1(), atoir(), ClientData::boardnm, childid, AddLineArg::clientdata, clnt_create(), ClientData::color, endtheclient(), gethostname(), ClientData::machinenm, mousewatch(), ClientData::nprogram, ClientData::nversion, openxwindow(), parentid, readndraw(), sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, sigaction(), sigemptyset(), WhiteBoardServer, WhiteBoardServerVersion, ClientData::xdisplaynm, and xwinio.
Referenced by main().
static void whiteboardclient_1 (struct svc_req * rqstp, register SVCXPRT * transp) [static]
Definition at line 20 of file client_s.c.
References callbackfromwbs, callbackfromwbs_1_svc(), NULL, NULLPROC, svc_req::rq_proc, svc_freeargs, svc_getargs, svc_sendreply(), svcerr_decode(), svcerr_noproc(), svcerr_systemerr(), xdr_OneLn(), and xdr_void().
Referenced by main().